matrix:
  include:
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

install:

script:
- cd tests
- ./run_test
