#!/usr/bin/env python3

import sys
import os

arguments = ""
for x in sys.argv:
    arguments += x + '\n'

env = ""
for x in ["CONTENT_LENGTH", "CONTENT_TYPE", "GATEWAY_INTERFACE", "REQUEST_URL", "SCRIPT_NAME"]:
    env += x + '=' + os.environ[x] + '\n'

customized_message = "Hello CGI!\nBasic CGI POST Test! The server should return this message at the end!\n"

content_length = str(len(arguments) + len(env) + len(customized_message))
header="HTTP/1.1 200 OK\nServer: ice\nContent-Length: " + content_length + "\nContent-Type: text/html\n\n"

print(header, end='')
print(arguments, end='')
print(env, end='')
print(customized_message, end='')
